try:
    from yppm import main
except Exception as e:
    print(e)
    import main
